// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package event

type Event struct {
	Url          string `json:"url"`
	Slug         string `json:"slug"`
	Name         string `json:"name"`
	Location     string `json:"location"`
	Organization string `json:"organization"`
	Image        string `json:"image"`
	Date         int64  `json:"date"`
	Fights       string `json:"fights"`
	History      string `json:"history"`
}

type Tapology struct {
	Name string `json:"name"`
	Url  string `json:"url"`
}
