// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package events

type DbEvent struct {
	Url     string `json:"url"`
	Data    []byte `json:"data"`
	History []byte `json:"history"`
}
